services:
  db:
    image: pgvector/pgvector:pg17
    restart: always
    environment:
      - POSTGRES_USER=route_admin
      - POSTGRES_PASSWORD=route_admin
      - POSTGRES_DB=jobsdb
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: