"""add_oauth_support

Revision ID: 20e8dae6e1a8
Revises: d5876421c708
Create Date: 2025-11-06 12:46:01.567938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20e8dae6e1a8'
down_revision: Union[str, Sequence[str], None] = 'd5876421c708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add auth_provider as NULLABLE first (to allow existing rows)
    op.add_column('users', sa.Column('auth_provider', sa.String(length=20), nullable=True))
    
    # Update all existing users to have 'local' as auth_provider
    op.execute("UPDATE users SET auth_provider = 'local' WHERE auth_provider IS NULL")
    
    # Now make it NOT NULL
    op.alter_column('users', 'auth_provider',
                    existing_type=sa.String(length=20),
                    nullable=False)
    
    # Add google_id (nullable is fine)
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    
    # Make password nullable for OAuth users
    op.alter_column('users', 'hashed_password',
                    existing_type=sa.String(length=255),
                    nullable=True)
    
    # Make username nullable for OAuth users  
    op.alter_column('users', 'username',
                    existing_type=sa.String(length=50),
                    nullable=True)
    
    # Add unique index on google_id
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    
    # Optional: Add check constraint for data integrity
    op.create_check_constraint(
        'auth_provider_fields_check',
        'users',
        "(auth_provider = 'local' AND hashed_password IS NOT NULL AND username IS NOT NULL) OR "
        "(auth_provider = 'google' AND google_id IS NOT NULL)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('auth_provider_fields_check', 'users', type_='check')
    
    # Remove index
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    
    # Make columns non-nullable again (WARNING: will fail if you have OAuth users!)
    op.alter_column('users', 'username', 
                    existing_type=sa.String(length=50),
                    nullable=False)
    op.alter_column('users', 'hashed_password',
                    existing_type=sa.String(length=255),
                    nullable=False)
    
    # Remove columns
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'auth_provider')
